package com.example.testmoh
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.ui.Modifier
import androidx.navigation.compose.rememberNavController
import com.example.testmoh.navigation.AppNavHost
import com.example.testmoh.ui.theme.TestMohTheme

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            // Apply your app's theme.
            // This theme is typically generated by Android Studio in ui/theme/Theme.kt.
            // Make sure the import and the function call match your generated theme name.
            TestMohTheme {
                // A surface container using the 'background' color from the theme.
                // It fills the entire screen of the device.
                Surface(
                    modifier = Modifier.fillMaxSize(),
                    color = MaterialTheme.colorScheme.background
                ) {

                    val navController = rememberNavController()

                    // Use our AppNavHost Composable.
                    // This is where all your defined onboarding screens will be managed and displayed.
                    // The AppNavHost determines which screen is shown based on the current navigation route.
                    AppNavHost(navController = navController)
                }
            }
        }
    }
}
